# Use an official Python runtime as a parent image
from python:3.10-slim-buster

# Set the working directory in the container
WORKDIR /transactions_backend

# Install python-dotenv to load environment variables from .env file
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
# RUN pip install python-dotenv

RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2
# Copy the requirements file into the container at /code
COPY requirements.txt /transactions_backend/

# Install the dependencies
RUN pip install -r requirements.txt


# Copy the current directory contents into the container at /code
COPY . /transactions_backend/
EXPOSE 8008

# Load environment variables from .env file
CMD ["python", "manage.py", "runserver", "0.0.0.0:8008"]
