# Generated by Django 5.0.2 on 2024-02-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionId', models.IntegerField(primary_key=True, serialize=False)),
                ('sellerId', models.IntegerField()),
                ('buyerId', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listingId', models.IntegerField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
