# Generated by Django 5.0.2 on 2024-02-25 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transactions_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='date_time',
        ),
    ]
