# Generated by Django 5.0.2 on 2024-03-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transactions_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
