version: "3"

networks:
  own-net:
    name: own-net
    driver: bridge

volumes:
  backend_node_modules:
  frontend_node_modules:

services:
  # Remove this service before submitting!
  #######################################################################
  # backend:
  #   build: ./backend
  #   container_name: backend
  #   networks:
  #     - own-net
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./backend:/app
  #     - ./backend/node_modules:/app/node_modules

  # ping-backend:
  #   build: ./ping-backend
  #   container_name: ping-backend
  #   networks:
  #     - own-net
  #   # ports:
  #   #   - "4000:4000"
  #   volumes:
  #     - ./ping-backend:/app
  #     - /app/node_modules
  #   command: npm start
  #   depends_on:
  #     - frontend

  # # ONLY FOR TESTING SENDING TO RABBITMQ
  # sender:
  #   build: ./send-notification
  #   container_name: send-notification
  #   hostname: send-notification
  #   ports:
  #     - "5001:5001"
  #   networks:
  #     - own-net
  #   depends_on:
  #     - emailer
  #######################################################################

  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   networks:
  #     - own-net
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   command: npm run dev
  #   depends_on:
  #     - backend

  transactions_backend:
    build: ./transactions_backend
    container_name: transactions_backend
    networks:
      - own-net
    ports:
      - "8000:8000"

  bid_microservice:
    build: ./bid_microservice/service
    container_name: bid_microservice
    networks:
      - own-net
    ports:
      - "3012:3012"

  # notification-rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: notification-rabbitmq
  #   hostname: notification-rabbitmq
  #   networks:
  #     - own-net
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   volumes:
  #     - ./notification-rabbitmq/conf.d:/etc/rabbitmq/conf.d

  # emailer:
  #   build: ./emailer
  #   container_name: emailer
  #   hostname: emailer
  #   networks:
  #     - own-net
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   depends_on:
  #     - notification-rabbitmq

  listings:
    build: ./Listings
    container_name: listings
    ports:
      - "3001:3001"
    networks:
      - own-net
    volumes:
      - ./Listings/serviceAccountKeyListings.json:/usr/src/app/serviceAccountKeyListings.json

  payment-complex:
    build: ./payment-complex
    container_name: payment-complex
    ports:
      - "3031:4000"
    networks:
      - own-net

  # bid-for-listing-complex:
  #   build: ./bid-for-listing-complex
  #   container_name: bid-for-listing-complex
  #   environment:
  #     - LISTING_SIMPLE_PORT_NUM=3001
  #     - BID_SIMPLE_PORT_NUM=3012
  #   ports:
  #     - "3015:3000"
  #   networks:
  #     - own-net
