version: "3"

networks:
  own-net:
    name: own-net
    driver: bridge

volumes:
  backend_node_modules:
  frontend_node_modules:

services:
  backend:
    build: ./backend
    container_name: backend
    networks:
      - own-net
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - own-net
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend

  ping-backend:
    build: ./ping-backend
    container_name: ping-backend
    networks:
      - own-net
    # ports:
    #   - "4000:4000"
    volumes:
      - ./ping-backend:/app
      - /app/node_modules
    command: npm start
    depends_on:
      - frontend

  # notification-rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: notification-rabbitmq
  #   hostname: notification-rabbitmq
  #   networks:
  #     - own-net
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   volumes:
  #     - ./notification-rabbitmq/conf.d:/etc/rabbitmq/conf.d

  # emailer:
  #   build: ./emailer
  #   container_name: emailer
  #   hostname: emailer
  #   networks:
  #     - own-net
  #   depends_on:
  #     - notification-rabbitmq

  # sender:
  #   build: ./send-notification
  #   container_name: send-notification
  #   hostname: send-notification
  #   ports:
  #     - "5001:5001"
  #   networks:
  #     - own-net
  #   depends_on:
  #     - emailer
